### ISSUE TITLE
Implement logs to all robot version

### ISSUE THREAD

**Issue by renanmedina** [renanmedina/lattesrobot#9]
Implement logs system on all robot versions to handle issues like exceptions, success and fatal errors for applications.

**Comment by jaarsi** [comment]
any name pattern to log file ? likes "lattesrobot_yyyymmdd_hhnnss.log"

**Comment by renanmedina** [comment]
You can use **lattesrobot_yyyymmdd.log** to store logs by day or you also can use a unique file named **lattesrobot.log** and store all logs where each line should be like:

[yyyymmddhhiiss][error/success/exception][description]
For example:

- **20170415163133 [SUCCESS] file xxxxx downloaded to /path/output successfully.**
- **20170415162910 [ERROR] file xxxxx could not be downloaded.**

**Comment by renanmedina** [comment]
The project is dead since Lattes new system is Down. closing it.
